services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codeigniter-app
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    networks:
      - codeigniter-network

networks:
  codeigniter-network:
    driver: bridge 